database:
  host: 1Panel-mysql-TUuu
  port: 3306
  dbname: app_db
  user: test
  password: D7p6ZkcJRMynPfCy

redis:
  host: 1Panel-redis-dpZp
  port: 6379
  password: 32wB6ejWwb78cPKT
  db: 0

jwt:
  secret: se123abc456
  expire_time: 7200
  refresh_expire_time: 604800 

server:
  port: 8080

storage:
  type: minio
  minio:
    endpoint: localhost:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: videos
    use_ssl: false
    public_host: http://localhost:9000
  s3:
    region: us-east-1
    access_key: ""
    secret_key: ""
    bucket: ""
    public_host: ""
  oss:
    endpoint: ""
    access_key: ""
    secret_key: ""
    bucket: ""
    public_host: ""
